version: '3'

services:
  php-fpm:
    container_name: crawler-php-fpm
    build: ./docker/php
    volumes:
      - .:/var/www
      - ./public:/var/www/html
  nginx:
    image: nginx:1.14-alpine
    container_name: crawler-nginx
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
      - .:/var/www
      - ./public:/var/www/html
